### ISSUE TITLE
Error inside package

### ISSUE THREAD

**Issue by dapearce** [tomwasd/flow-router-seo#2]
I'm trying to use this inside a package and getting the following error:

`Uncaught TypeError: Cannot read property 'extend' of undefined flow-router-seo.js:120`

The only code I have now is creating the `new FlowRouterSEO()` and trying to set the defaults (in client). If I comment out the `setDefaults` I get no errors.

Any idea what might be causing this?

**Comment by tomwasd** [comment]
Hi @dapearce,

At a guess I think this is because I forgot to put `api.use(['jquery']);` in `package.js` and so in your case jquery isn't loaded prior to flow-router-seo and so you don't have access to jquery's `extend` function.

I've pushed a new version to github and atmosphere. Fingers crossed that resolves your problem but just shout if not and I'll have a more thorough look!

**Comment by dapearce** [comment]
Yes that seems to have solved the issue, thanks!
