### ISSUE TITLE
kadira:dochead vs flow-router-seo?

### ISSUE THREAD

**Issue by thearabbit** [tomwasd/flow-router-seo#3]
What difference of kadira:dochead vs flow-router-seo?

**Comment by tomwasd** [comment]
Hi @thearabbit,

Afraid I haven't had time to get to grips with kadira:dochead yet but I believe it simply provides a way to set individual title/meta tags.

flow-router-seo allows you to set default meta values, automatically sets twitter/opengraph title, description and url fields and allows you to store static title/meta information in a database.

The plan is for flow-router-seo to utilise kadira:dochead in the future so that this package supports SSR as well.

Hope that all makes sense,

Tom

**Comment by thearabbit** [comment]
Thanks.
