### ISSUE TITLE
Could I configure "SEO" with router name at one place?

### ISSUE THREAD

**Issue by thearabbit** [tomwasd/flow-router-seo#4]
I want to configure `SEO` with router name at one place.
Because I think that it is difficult to maintenance if we configure it at all of `Template........onCreated()`.

**Comment by tomwasd** [comment]
Hi @thearabbit,

You could create a separate file that just dealt with SEO and had multiple `Template.templateName.onCreated()` functions in just dealing with the SEO of that page.

If you have Template level subscriptions then I've assumed you'll need to set the SEO data within each template. If the SEO data isn't dynamic then you could consider using the database option to store the information.

Hope that helps,

Tom

**Comment by thearabbit** [comment]
Thank for your reply.
Please example for `You could create a separate file that just...`

**Comment by tomwasd** [comment]
Hi @thearabbit,

Say you had 3 templates called 'templateA', 'templateB' and 'templateC'.

You could create a file called 'seo.js'

In that file you'd have:

```
Template.templateA.onCreated(function() {
   // SEO configuration for templateA
});

Template.templateB.onCreated(function() {
   // SEO configuration for templateB
});

Template.templateC.onCreated(function() {
   // SEO configuration for templateC
});
```

**Comment by thearabbit** [comment]
What do you think, If we config with route name

``` js
SEO.set('routerName',
 {
    title: 'Title for this template',
    description: 'Description for this template',
    meta: {
      'property="og:image"': 'http://locationofimage.com/image.png'
    }
  });
   .set()
   .set();
```

So we can use it in one place.

**Comment by tomwasd** [comment]
Hi @thearabbit,

I think we might have our wires crossed as to what you're after.

If you have routes with fixed SEO data then it's probably best to use the database option and then:

```
SEO.routes.upsert({routeName: 'home'}, {$set: {
  title: 'Home page',
  description: 'A lovely place to be',
  meta: {
    'property="og:image"': 'http://locationofimage.com/image.png'
  }
}})
```

Otherwise, if the SEO data is dynamic and depends on the subscription data then it'll need to be set after the subscription is ready and so (assuming template level subscriptions) will have to be set at the template level.

I might be misunderstanding - if I have then if you could chuck an example my way I'll see if I can work out what you're after and how the package needs to be tweaked.

Thanks,

Tom

**Comment by thearabbit** [comment]
Thanks for your explain.
I close this.
